package rr.thaiicecoffee.sitegenerator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

import rr.thaiicecoffee.sitegenerator.stylesheet.Stylesheet;

public class Website {
	
	static final String NAVBAR_START = "<div class='navbar'>";
	static final String NAVBAR_END = "</div>";
	static final String OUTPUT_FOLDER = "site";
	
	static final String SIGNATURE = "\n<!--This page was generated by ThaiIceCoffee -->";
	
	private ArrayList<Webpage> pages;
	
	private String commonTitle;
	private Stylesheet commonStylesheet;
	private boolean commonNavBar;
	
	public Website() {
		pages = new ArrayList<Webpage>();
		
		commonNavBar = false;
	}
	
	public void addCommonTitle(String title) {
		commonTitle = title;
	}
	
	public void addCommonNavBar() {
		commonNavBar = true;
	}
	
	public void addPage(Webpage page) {
		pages.add(page);
	}
	
	public void addCommonStylesheet(Stylesheet stylesheet) {
		commonStylesheet = stylesheet;
	}
	
	public void generateWebsite(String path) throws IOException {
		
		File siteFolder = new File(OUTPUT_FOLDER);
		siteFolder.mkdir();
		if (commonNavBar) {
			String navBarSource = NAVBAR_START;
			for (Webpage page : pages) {
				navBarSource += "<a href='" + page.getName() + "'>" 
								+ page.getName() + "</a>";
			}
			navBarSource += NAVBAR_END;
			
			for (Webpage page : pages) {
				page.prependDiv(navBarSource);
			}
		}
		if (commonStylesheet != null) {
			File file = new File(OUTPUT_FOLDER + "/" + commonStylesheet.getName());
			file.createNewFile();
			FileWriter fw = new FileWriter(file);
			fw.write(commonStylesheet.getSource());
			fw.close();
		}
		
		for (Webpage page : pages) {
			if (commonTitle != null && page.getTitle() == null) {
				page.setTitle(commonTitle);
			}
			if (commonStylesheet != null) {
				page.addStyleSheet(commonStylesheet.getName());
			}
			File file = new File(OUTPUT_FOLDER + "/" + page.getName());
			file.createNewFile();
			FileWriter fw = new FileWriter(file);
			fw.write(page.getPageSource() + SIGNATURE);
			fw.close();
			
		}
	}
}
